// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOperationLog = "sys_operation_log"

// OperationLog 操作日志表
type OperationLog struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:日志ID" json:"id"`                         // 日志ID
	Title         *string   `gorm:"column:title;type:varchar(64);comment:模块标题" json:"title"`                                            // 模块标题
	BusinessType  *int64    `gorm:"column:business_type;type:tinyint(1);default:4;comment:业务类型（1新增 2修改 3删除 4其它）" json:"business_type"`  // 业务类型（1新增 2修改 3删除 4其它）
	Method        *string   `gorm:"column:method;type:varchar(128);comment:方法名称" json:"method"`                                         // 方法名称
	RequestMethod *string   `gorm:"column:request_method;type:varchar(10);comment:请求方式" json:"request_method"`                          // 请求方式
	OperatorType  *int64    `gorm:"column:operator_type;type:tinyint(1);default:3;comment:操作类别（1后台用户 2手机端用户 3其它）" json:"operator_type"` // 操作类别（1后台用户 2手机端用户 3其它）
	UserID        *int64    `gorm:"column:user_id;type:bigint;comment:操作人ID" json:"user_id"`                                            // 操作人ID
	Username      *string   `gorm:"column:username;type:varchar(64);comment:操作人名称" json:"username"`                                     // 操作人名称
	URL           *string   `gorm:"column:url;type:varchar(255);comment:请求URL" json:"url"`                                              // 请求URL
	IP            *string   `gorm:"column:ip;type:varchar(50);comment:操作地址" json:"ip"`                                                  // 操作地址
	Location      *string   `gorm:"column:location;type:varchar(64);comment:操作地点" json:"location"`                                      // 操作地点
	Browser       *string   `gorm:"column:browser;type:varchar(50);comment:浏览器类型" json:"browser"`                                       // 浏览器类型
	Os            *string   `gorm:"column:os;type:varchar(50);comment:操作系统" json:"os"`                                                  // 操作系统
	Device        *string   `gorm:"column:device;type:varchar(50);comment:设备" json:"device"`                                            // 设备
	Param         *string   `gorm:"column:param;type:text;comment:请求参数" json:"param"`                                                   // 请求参数
	Result        *string   `gorm:"column:result;type:text;comment:返回结果" json:"result"`                                                 // 返回结果
	Status        *int64    `gorm:"column:status;type:tinyint(1);default:1;comment:操作状态（1正常 2异常）" json:"status"`                        // 操作状态（1正常 2异常）
	ErrorStack    *string   `gorm:"column:error_stack;type:text;comment:错误消息" json:"error_stack"`                                       // 错误消息
	CostTime      *int64    `gorm:"column:cost_time;type:bigint;comment:消耗时间" json:"cost_time"`                                         // 消耗时间
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                            // 创建时间
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
