// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameRoleMenu = "sys_role_menu"

// RoleMenu 角色菜单关联表
type RoleMenu struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	RoleID    int64     `gorm:"column:role_id;type:bigint;not null;comment:角色ID" json:"role_id"`          // 角色ID
	MenuID    int64     `gorm:"column:menu_id;type:bigint;not null;comment:菜单ID" json:"menu_id"`          // 菜单ID
	CreatedBy *int64    `gorm:"column:created_by;type:bigint;comment:创建人" json:"created_by"`              // 创建人
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`  // 创建时间
	Role      *Role     `gorm:"foreignKey:RoleID;references:ID" json:"role"`
	Menu      *Menu     `gorm:"foreignKey:MenuID;references:ID" json:"menu"`
}

// TableName RoleMenu's table name
func (*RoleMenu) TableName() string {
	return TableNameRoleMenu
}
