// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDictData = "sys_dict_data"

// DictData 字典数据表
type DictData struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:字典数据ID" json:"id"`       // 字典数据ID
	DictType  string         `gorm:"column:dict_type;type:varchar(64);not null;comment:字典类型" json:"dict_type"`           // 字典类型
	DictLabel string         `gorm:"column:dict_label;type:varchar(128);not null;comment:字典标签" json:"dict_label"`        // 字典标签
	DictValue string         `gorm:"column:dict_value;type:varchar(128);not null;comment:字典值" json:"dict_value"`         // 字典值
	DictSort  *int64         `gorm:"column:dict_sort;type:int;comment:排序" json:"dict_sort"`                              // 排序
	CSSClass  *string        `gorm:"column:css_class;type:varchar(128);comment:样式属性" json:"css_class"`                   // 样式属性
	ListClass *string        `gorm:"column:list_class;type:varchar(128);comment:表格回显样式" json:"list_class"`               // 表格回显样式
	IsDefault *int64         `gorm:"column:is_default;type:tinyint(1);default:2;comment:是否默认 1-是 2-否" json:"is_default"` // 是否默认 1-是 2-否
	Status    *int64         `gorm:"column:status;type:tinyint(1);default:1;comment:状态 1-正常 2-禁用" json:"status"`         // 状态 1-正常 2-禁用
	Remark    *string        `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                           // 备注
	CreatedBy *int64         `gorm:"column:created_by;type:bigint;comment:创建人" json:"created_by"`                        // 创建人
	UpdatedBy *int64         `gorm:"column:updated_by;type:bigint;comment:更新人" json:"updated_by"`                        // 更新人
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`            // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                     // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                     // 删除时间
	Version   *int64         `gorm:"column:version;type:int;comment:乐观锁版本" json:"version"`                               // 乐观锁版本
	Type      *DictType      `gorm:"foreignKey:DictType;references:Type" json:"dictType"`
}

// TableName DictData's table name
func (*DictData) TableName() string {
	return TableNameDictData
}
