// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameLoginLog = "sys_login_log"

// LoginLog 登录日志表
type LoginLog struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:访问ID" json:"id"`  // 访问ID
	UID       int64     `gorm:"column:uid;type:bigint;not null;comment:用户ID" json:"uid"`                     // 用户ID
	IP        *string   `gorm:"column:ip;type:varchar(50);comment:登录IP地址" json:"ip"`                         // 登录IP地址
	Location  *string   `gorm:"column:location;type:varchar(64);comment:登录地点" json:"location"`               // 登录地点
	Browser   *string   `gorm:"column:browser;type:varchar(50);comment:浏览器类型" json:"browser"`                // 浏览器类型
	Os        *string   `gorm:"column:os;type:varchar(50);comment:操作系统" json:"os"`                           // 操作系统
	Device    *string   `gorm:"column:device;type:varchar(50);comment:设备" json:"device"`                     // 设备
	Status    *int64    `gorm:"column:status;type:tinyint(1);default:1;comment:登录状态（1成功 2失败）" json:"status"` // 登录状态（1成功 2失败）
	Msg       *string   `gorm:"column:msg;type:varchar(64);comment:提示消息" json:"msg"`                         // 提示消息
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`     // 创建时间
}

// TableName LoginLog's table name
func (*LoginLog) TableName() string {
	return TableNameLoginLog
}
