// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDept = "sys_dept"

// Dept 部门表
type Dept struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:部门ID" json:"id"` // 部门ID
	Pid       *int64         `gorm:"column:pid;type:bigint;comment:父部门ID" json:"pid"`                            // 父部门ID
	Name      string         `gorm:"column:name;type:varchar(64);not null;comment:部门名称" json:"name"`             // 部门名称
	Code      *string        `gorm:"column:code;type:varchar(32);comment:部门编码" json:"code"`                      // 部门编码
	Ancestors *string        `gorm:"column:ancestors;type:varchar(255);comment:祖级列表" json:"ancestors"`           // 祖级列表
	Leader    *string        `gorm:"column:leader;type:varchar(64);comment:负责人" json:"leader"`                   // 负责人
	Phone     *string        `gorm:"column:phone;type:varchar(16);comment:联系电话" json:"phone"`                    // 联系电话
	Email     *string        `gorm:"column:email;type:varchar(64);comment:邮箱" json:"email"`                      // 邮箱
	Sort      *int64         `gorm:"column:sort;type:int;comment:排序" json:"sort"`                                // 排序
	Status    *int64         `gorm:"column:status;type:tinyint(1);default:1;comment:状态 1-正常 2-禁用" json:"status"` // 状态 1-正常 2-禁用
	CreatedBy *int64         `gorm:"column:created_by;type:bigint;comment:创建人" json:"created_by"`                // 创建人
	UpdatedBy *int64         `gorm:"column:updated_by;type:bigint;comment:更新人" json:"updated_by"`                // 更新人
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`             // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`             // 删除时间
	Version   *int64         `gorm:"column:version;type:int;comment:乐观锁版本" json:"version"`                       // 乐观锁版本
	Parent    *Dept          `gorm:"foreignKey:Pid;references:ID" json:"parent"`
	Children  []*Dept        `gorm:"foreignKey:Pid;references:ID" json:"children"`
	Users     []*User        `gorm:"foreignKey:DeptID;references:ID" json:"users"`
}

// TableName Dept's table name
func (*Dept) TableName() string {
	return TableNameDept
}
