// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "sys_user"

// User 系统用户表
type User struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`    // 用户ID
	Username  string         `gorm:"column:username;type:varchar(64);not null;comment:用户名" json:"username"`         // 用户名
	Password  string         `gorm:"column:password;type:varchar(128);not null;comment:密码" json:"password"`         // 密码
	Salt      *string        `gorm:"column:salt;type:varchar(16);comment:加密盐" json:"salt"`                          // 加密盐
	RealName  *string        `gorm:"column:real_name;type:varchar(64);comment:真实姓名" json:"real_name"`               // 真实姓名
	NickName  *string        `gorm:"column:nick_name;type:varchar(64);comment:昵称" json:"nick_name"`                 // 昵称
	Avatar    *string        `gorm:"column:avatar;type:varchar(255);comment:头像地址" json:"avatar"`                    // 头像地址
	Email     *string        `gorm:"column:email;type:varchar(128);comment:邮箱" json:"email"`                        // 邮箱
	Mobile    *string        `gorm:"column:mobile;type:varchar(20);comment:手机号" json:"mobile"`                      // 手机号
	Gender    *int64         `gorm:"column:gender;type:tinyint(1);default:3;comment:性别 1-男 2-女 3-未知" json:"gender"` // 性别 1-男 2-女 3-未知
	DeptID    *int64         `gorm:"column:dept_id;type:bigint;comment:部门ID" json:"dept_id"`                        // 部门ID
	PostID    *int64         `gorm:"column:post_id;type:bigint;comment:岗位ID" json:"post_id"`                        // 岗位ID
	RoleID    *int64         `gorm:"column:role_id;type:bigint;comment:角色ID" json:"role_id"`                        // 角色ID
	Remark    *string        `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                      // 备注
	Status    *int64         `gorm:"column:status;type:tinyint(1);default:1;comment:状态 1-正常 2-禁用" json:"status"`    // 状态 1-正常 2-禁用
	CreatedBy *int64         `gorm:"column:created_by;type:bigint;comment:创建人" json:"created_by"`                   // 创建人
	UpdatedBy *int64         `gorm:"column:updated_by;type:bigint;comment:更新人" json:"updated_by"`                   // 更新人
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`       // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                // 删除时间
	Version   *int64         `gorm:"column:version;type:int;comment:乐观锁版本" json:"version"`                          // 乐观锁版本
	Role      *Role          `gorm:"foreignKey:RoleID;references:ID" json:"role"`
	Dept      *Dept          `gorm:"foreignKey:DeptID;references:ID" json:"dept"`
	Post      *Post          `gorm:"foreignKey:PostID;references:ID" json:"post"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
