// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sweet/internal/models/entity"
)

func newSysUser(db *gorm.DB, opts ...gen.DOOption) sysUser {
	_sysUser := sysUser{}

	_sysUser.sysUserDo.UseDB(db, opts...)
	_sysUser.sysUserDo.UseModel(&entity.SysUser{})

	tableName := _sysUser.sysUserDo.TableName()
	_sysUser.ALL = field.NewAsterisk(tableName)
	_sysUser.ID = field.NewInt64(tableName, "id")
	_sysUser.Username = field.NewString(tableName, "username")
	_sysUser.Password = field.NewString(tableName, "password")
	_sysUser.Salt = field.NewString(tableName, "salt")
	_sysUser.Realname = field.NewString(tableName, "realname")
	_sysUser.Nickname = field.NewString(tableName, "nickname")
	_sysUser.Avatar = field.NewString(tableName, "avatar")
	_sysUser.Email = field.NewString(tableName, "email")
	_sysUser.Phone = field.NewString(tableName, "phone")
	_sysUser.Status = field.NewInt64(tableName, "status")
	_sysUser.RoleID = field.NewInt64(tableName, "role_id")
	_sysUser.DeptID = field.NewInt64(tableName, "dept_id")
	_sysUser.PostID = field.NewInt64(tableName, "post_id")
	_sysUser.Remark = field.NewString(tableName, "remark")
	_sysUser.CreatedAt = field.NewTime(tableName, "created_at")
	_sysUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysUser.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysUser.Role = sysUserBelongsToRole{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Role", "entity.SysRole"),
	}

	_sysUser.Dept = sysUserBelongsToDept{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Dept", "entity.SysDept"),
	}

	_sysUser.Post = sysUserBelongsToPost{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Post", "entity.SysPost"),
	}

	_sysUser.fillFieldMap()

	return _sysUser
}

// sysUser 系统管理员表
type sysUser struct {
	sysUserDo

	ALL       field.Asterisk
	ID        field.Int64  // 管理员ID
	Username  field.String // 登录用户名
	Password  field.String // 登录密码
	Salt      field.String // 密码盐
	Realname  field.String // 真实姓名
	Nickname  field.String // 昵称
	Avatar    field.String // 头像
	Email     field.String // 邮箱
	Phone     field.String // 手机号
	Status    field.Int64  // 状态：1=正常，2=禁用
	RoleID    field.Int64  // 角色ID
	DeptID    field.Int64  // 部门ID
	PostID    field.Int64  // 岗位ID
	Remark    field.String // 备注
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间
	Role      sysUserBelongsToRole

	Dept sysUserBelongsToDept

	Post sysUserBelongsToPost

	fieldMap map[string]field.Expr
}

func (s sysUser) Table(newTableName string) *sysUser {
	s.sysUserDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUser) As(alias string) *sysUser {
	s.sysUserDo.DO = *(s.sysUserDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUser) updateTableName(table string) *sysUser {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Username = field.NewString(table, "username")
	s.Password = field.NewString(table, "password")
	s.Salt = field.NewString(table, "salt")
	s.Realname = field.NewString(table, "realname")
	s.Nickname = field.NewString(table, "nickname")
	s.Avatar = field.NewString(table, "avatar")
	s.Email = field.NewString(table, "email")
	s.Phone = field.NewString(table, "phone")
	s.Status = field.NewInt64(table, "status")
	s.RoleID = field.NewInt64(table, "role_id")
	s.DeptID = field.NewInt64(table, "dept_id")
	s.PostID = field.NewInt64(table, "post_id")
	s.Remark = field.NewString(table, "remark")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUser) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 20)
	s.fieldMap["id"] = s.ID
	s.fieldMap["username"] = s.Username
	s.fieldMap["password"] = s.Password
	s.fieldMap["salt"] = s.Salt
	s.fieldMap["realname"] = s.Realname
	s.fieldMap["nickname"] = s.Nickname
	s.fieldMap["avatar"] = s.Avatar
	s.fieldMap["email"] = s.Email
	s.fieldMap["phone"] = s.Phone
	s.fieldMap["status"] = s.Status
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["dept_id"] = s.DeptID
	s.fieldMap["post_id"] = s.PostID
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt

}

func (s sysUser) clone(db *gorm.DB) sysUser {
	s.sysUserDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Role.db = db.Session(&gorm.Session{Initialized: true})
	s.Role.db.Statement.ConnPool = db.Statement.ConnPool
	s.Dept.db = db.Session(&gorm.Session{Initialized: true})
	s.Dept.db.Statement.ConnPool = db.Statement.ConnPool
	s.Post.db = db.Session(&gorm.Session{Initialized: true})
	s.Post.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysUser) replaceDB(db *gorm.DB) sysUser {
	s.sysUserDo.ReplaceDB(db)
	s.Role.db = db.Session(&gorm.Session{})
	s.Dept.db = db.Session(&gorm.Session{})
	s.Post.db = db.Session(&gorm.Session{})
	return s
}

type sysUserBelongsToRole struct {
	db *gorm.DB

	field.RelationField
}

func (a sysUserBelongsToRole) Where(conds ...field.Expr) *sysUserBelongsToRole {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysUserBelongsToRole) WithContext(ctx context.Context) *sysUserBelongsToRole {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysUserBelongsToRole) Session(session *gorm.Session) *sysUserBelongsToRole {
	a.db = a.db.Session(session)
	return &a
}

func (a sysUserBelongsToRole) Model(m *entity.SysUser) *sysUserBelongsToRoleTx {
	return &sysUserBelongsToRoleTx{a.db.Model(m).Association(a.Name())}
}

func (a sysUserBelongsToRole) Unscoped() *sysUserBelongsToRole {
	a.db = a.db.Unscoped()
	return &a
}

type sysUserBelongsToRoleTx struct{ tx *gorm.Association }

func (a sysUserBelongsToRoleTx) Find() (result *entity.SysRole, err error) {
	return result, a.tx.Find(&result)
}

func (a sysUserBelongsToRoleTx) Append(values ...*entity.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysUserBelongsToRoleTx) Replace(values ...*entity.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysUserBelongsToRoleTx) Delete(values ...*entity.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysUserBelongsToRoleTx) Clear() error {
	return a.tx.Clear()
}

func (a sysUserBelongsToRoleTx) Count() int64 {
	return a.tx.Count()
}

func (a sysUserBelongsToRoleTx) Unscoped() *sysUserBelongsToRoleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysUserBelongsToDept struct {
	db *gorm.DB

	field.RelationField
}

func (a sysUserBelongsToDept) Where(conds ...field.Expr) *sysUserBelongsToDept {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysUserBelongsToDept) WithContext(ctx context.Context) *sysUserBelongsToDept {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysUserBelongsToDept) Session(session *gorm.Session) *sysUserBelongsToDept {
	a.db = a.db.Session(session)
	return &a
}

func (a sysUserBelongsToDept) Model(m *entity.SysUser) *sysUserBelongsToDeptTx {
	return &sysUserBelongsToDeptTx{a.db.Model(m).Association(a.Name())}
}

func (a sysUserBelongsToDept) Unscoped() *sysUserBelongsToDept {
	a.db = a.db.Unscoped()
	return &a
}

type sysUserBelongsToDeptTx struct{ tx *gorm.Association }

func (a sysUserBelongsToDeptTx) Find() (result *entity.SysDept, err error) {
	return result, a.tx.Find(&result)
}

func (a sysUserBelongsToDeptTx) Append(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysUserBelongsToDeptTx) Replace(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysUserBelongsToDeptTx) Delete(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysUserBelongsToDeptTx) Clear() error {
	return a.tx.Clear()
}

func (a sysUserBelongsToDeptTx) Count() int64 {
	return a.tx.Count()
}

func (a sysUserBelongsToDeptTx) Unscoped() *sysUserBelongsToDeptTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysUserBelongsToPost struct {
	db *gorm.DB

	field.RelationField
}

func (a sysUserBelongsToPost) Where(conds ...field.Expr) *sysUserBelongsToPost {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysUserBelongsToPost) WithContext(ctx context.Context) *sysUserBelongsToPost {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysUserBelongsToPost) Session(session *gorm.Session) *sysUserBelongsToPost {
	a.db = a.db.Session(session)
	return &a
}

func (a sysUserBelongsToPost) Model(m *entity.SysUser) *sysUserBelongsToPostTx {
	return &sysUserBelongsToPostTx{a.db.Model(m).Association(a.Name())}
}

func (a sysUserBelongsToPost) Unscoped() *sysUserBelongsToPost {
	a.db = a.db.Unscoped()
	return &a
}

type sysUserBelongsToPostTx struct{ tx *gorm.Association }

func (a sysUserBelongsToPostTx) Find() (result *entity.SysPost, err error) {
	return result, a.tx.Find(&result)
}

func (a sysUserBelongsToPostTx) Append(values ...*entity.SysPost) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysUserBelongsToPostTx) Replace(values ...*entity.SysPost) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysUserBelongsToPostTx) Delete(values ...*entity.SysPost) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysUserBelongsToPostTx) Clear() error {
	return a.tx.Clear()
}

func (a sysUserBelongsToPostTx) Count() int64 {
	return a.tx.Count()
}

func (a sysUserBelongsToPostTx) Unscoped() *sysUserBelongsToPostTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysUserDo struct{ gen.DO }

type ISysUserDo interface {
	gen.SubQuery
	Debug() ISysUserDo
	WithContext(ctx context.Context) ISysUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysUserDo
	WriteDB() ISysUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysUserDo
	Not(conds ...gen.Condition) ISysUserDo
	Or(conds ...gen.Condition) ISysUserDo
	Select(conds ...field.Expr) ISysUserDo
	Where(conds ...gen.Condition) ISysUserDo
	Order(conds ...field.Expr) ISysUserDo
	Distinct(cols ...field.Expr) ISysUserDo
	Omit(cols ...field.Expr) ISysUserDo
	Join(table schema.Tabler, on ...field.Expr) ISysUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysUserDo
	Group(cols ...field.Expr) ISysUserDo
	Having(conds ...gen.Condition) ISysUserDo
	Limit(limit int) ISysUserDo
	Offset(offset int) ISysUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserDo
	Unscoped() ISysUserDo
	Create(values ...*entity.SysUser) error
	CreateInBatches(values []*entity.SysUser, batchSize int) error
	Save(values ...*entity.SysUser) error
	First() (*entity.SysUser, error)
	Take() (*entity.SysUser, error)
	Last() (*entity.SysUser, error)
	Find() ([]*entity.SysUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SysUser, err error)
	FindInBatches(result *[]*entity.SysUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.SysUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysUserDo
	Assign(attrs ...field.AssignExpr) ISysUserDo
	Joins(fields ...field.RelationField) ISysUserDo
	Preload(fields ...field.RelationField) ISysUserDo
	FirstOrInit() (*entity.SysUser, error)
	FirstOrCreate() (*entity.SysUser, error)
	FindByPage(offset int, limit int) (result []*entity.SysUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysUserDo) Debug() ISysUserDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserDo) WithContext(ctx context.Context) ISysUserDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserDo) ReadDB() ISysUserDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserDo) WriteDB() ISysUserDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserDo) Session(config *gorm.Session) ISysUserDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserDo) Clauses(conds ...clause.Expression) ISysUserDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserDo) Returning(value interface{}, columns ...string) ISysUserDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserDo) Not(conds ...gen.Condition) ISysUserDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserDo) Or(conds ...gen.Condition) ISysUserDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserDo) Select(conds ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserDo) Where(conds ...gen.Condition) ISysUserDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserDo) Order(conds ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserDo) Distinct(cols ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserDo) Omit(cols ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserDo) Join(table schema.Tabler, on ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserDo) Group(cols ...field.Expr) ISysUserDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserDo) Having(conds ...gen.Condition) ISysUserDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserDo) Limit(limit int) ISysUserDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserDo) Offset(offset int) ISysUserDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserDo) Unscoped() ISysUserDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserDo) Create(values ...*entity.SysUser) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserDo) CreateInBatches(values []*entity.SysUser, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserDo) Save(values ...*entity.SysUser) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserDo) First() (*entity.SysUser, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysUser), nil
	}
}

func (s sysUserDo) Take() (*entity.SysUser, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysUser), nil
	}
}

func (s sysUserDo) Last() (*entity.SysUser, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysUser), nil
	}
}

func (s sysUserDo) Find() ([]*entity.SysUser, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SysUser), err
}

func (s sysUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SysUser, err error) {
	buf := make([]*entity.SysUser, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserDo) FindInBatches(result *[]*entity.SysUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserDo) Attrs(attrs ...field.AssignExpr) ISysUserDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserDo) Assign(attrs ...field.AssignExpr) ISysUserDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserDo) Joins(fields ...field.RelationField) ISysUserDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserDo) Preload(fields ...field.RelationField) ISysUserDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserDo) FirstOrInit() (*entity.SysUser, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysUser), nil
	}
}

func (s sysUserDo) FirstOrCreate() (*entity.SysUser, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysUser), nil
	}
}

func (s sysUserDo) FindByPage(offset int, limit int) (result []*entity.SysUser, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserDo) Delete(models ...*entity.SysUser) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserDo) withDO(do gen.Dao) *sysUserDo {
	s.DO = *do.(*gen.DO)
	return s
}
