// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sweet/internal/models/entity"
)

func newSysDept(db *gorm.DB, opts ...gen.DOOption) sysDept {
	_sysDept := sysDept{}

	_sysDept.sysDeptDo.UseDB(db, opts...)
	_sysDept.sysDeptDo.UseModel(&entity.SysDept{})

	tableName := _sysDept.sysDeptDo.TableName()
	_sysDept.ALL = field.NewAsterisk(tableName)
	_sysDept.ID = field.NewInt64(tableName, "id")
	_sysDept.ParentID = field.NewInt64(tableName, "parent_id")
	_sysDept.Name = field.NewString(tableName, "name")
	_sysDept.Code = field.NewString(tableName, "code")
	_sysDept.Sort = field.NewInt64(tableName, "sort")
	_sysDept.Status = field.NewInt64(tableName, "status")
	_sysDept.CreatedAt = field.NewTime(tableName, "created_at")
	_sysDept.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysDept.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysDept.Parent = sysDeptBelongsToParent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parent", "entity.SysDept"),
	}

	_sysDept.Children = sysDeptHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "entity.SysDept"),
	}

	_sysDept.fillFieldMap()

	return _sysDept
}

// sysDept 部门表
type sysDept struct {
	sysDeptDo

	ALL       field.Asterisk
	ID        field.Int64  // 部门ID
	ParentID  field.Int64  // 父部门ID
	Name      field.String // 部门名称
	Code      field.String // 部门编码
	Sort      field.Int64  // 排序
	Status    field.Int64  // 状态: 1-启用, 2-禁用
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间
	Parent    sysDeptBelongsToParent

	Children sysDeptHasManyChildren

	fieldMap map[string]field.Expr
}

func (s sysDept) Table(newTableName string) *sysDept {
	s.sysDeptDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDept) As(alias string) *sysDept {
	s.sysDeptDo.DO = *(s.sysDeptDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDept) updateTableName(table string) *sysDept {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.ParentID = field.NewInt64(table, "parent_id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.Sort = field.NewInt64(table, "sort")
	s.Status = field.NewInt64(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysDept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDept) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt

}

func (s sysDept) clone(db *gorm.DB) sysDept {
	s.sysDeptDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Parent.db = db.Session(&gorm.Session{Initialized: true})
	s.Parent.db.Statement.ConnPool = db.Statement.ConnPool
	s.Children.db = db.Session(&gorm.Session{Initialized: true})
	s.Children.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysDept) replaceDB(db *gorm.DB) sysDept {
	s.sysDeptDo.ReplaceDB(db)
	s.Parent.db = db.Session(&gorm.Session{})
	s.Children.db = db.Session(&gorm.Session{})
	return s
}

type sysDeptBelongsToParent struct {
	db *gorm.DB

	field.RelationField
}

func (a sysDeptBelongsToParent) Where(conds ...field.Expr) *sysDeptBelongsToParent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysDeptBelongsToParent) WithContext(ctx context.Context) *sysDeptBelongsToParent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysDeptBelongsToParent) Session(session *gorm.Session) *sysDeptBelongsToParent {
	a.db = a.db.Session(session)
	return &a
}

func (a sysDeptBelongsToParent) Model(m *entity.SysDept) *sysDeptBelongsToParentTx {
	return &sysDeptBelongsToParentTx{a.db.Model(m).Association(a.Name())}
}

func (a sysDeptBelongsToParent) Unscoped() *sysDeptBelongsToParent {
	a.db = a.db.Unscoped()
	return &a
}

type sysDeptBelongsToParentTx struct{ tx *gorm.Association }

func (a sysDeptBelongsToParentTx) Find() (result *entity.SysDept, err error) {
	return result, a.tx.Find(&result)
}

func (a sysDeptBelongsToParentTx) Append(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysDeptBelongsToParentTx) Replace(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysDeptBelongsToParentTx) Delete(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysDeptBelongsToParentTx) Clear() error {
	return a.tx.Clear()
}

func (a sysDeptBelongsToParentTx) Count() int64 {
	return a.tx.Count()
}

func (a sysDeptBelongsToParentTx) Unscoped() *sysDeptBelongsToParentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysDeptHasManyChildren struct {
	db *gorm.DB

	field.RelationField
}

func (a sysDeptHasManyChildren) Where(conds ...field.Expr) *sysDeptHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysDeptHasManyChildren) WithContext(ctx context.Context) *sysDeptHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysDeptHasManyChildren) Session(session *gorm.Session) *sysDeptHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a sysDeptHasManyChildren) Model(m *entity.SysDept) *sysDeptHasManyChildrenTx {
	return &sysDeptHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

func (a sysDeptHasManyChildren) Unscoped() *sysDeptHasManyChildren {
	a.db = a.db.Unscoped()
	return &a
}

type sysDeptHasManyChildrenTx struct{ tx *gorm.Association }

func (a sysDeptHasManyChildrenTx) Find() (result []*entity.SysDept, err error) {
	return result, a.tx.Find(&result)
}

func (a sysDeptHasManyChildrenTx) Append(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysDeptHasManyChildrenTx) Replace(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysDeptHasManyChildrenTx) Delete(values ...*entity.SysDept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysDeptHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a sysDeptHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

func (a sysDeptHasManyChildrenTx) Unscoped() *sysDeptHasManyChildrenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysDeptDo struct{ gen.DO }

type ISysDeptDo interface {
	gen.SubQuery
	Debug() ISysDeptDo
	WithContext(ctx context.Context) ISysDeptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDeptDo
	WriteDB() ISysDeptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDeptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDeptDo
	Not(conds ...gen.Condition) ISysDeptDo
	Or(conds ...gen.Condition) ISysDeptDo
	Select(conds ...field.Expr) ISysDeptDo
	Where(conds ...gen.Condition) ISysDeptDo
	Order(conds ...field.Expr) ISysDeptDo
	Distinct(cols ...field.Expr) ISysDeptDo
	Omit(cols ...field.Expr) ISysDeptDo
	Join(table schema.Tabler, on ...field.Expr) ISysDeptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDeptDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDeptDo
	Group(cols ...field.Expr) ISysDeptDo
	Having(conds ...gen.Condition) ISysDeptDo
	Limit(limit int) ISysDeptDo
	Offset(offset int) ISysDeptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDeptDo
	Unscoped() ISysDeptDo
	Create(values ...*entity.SysDept) error
	CreateInBatches(values []*entity.SysDept, batchSize int) error
	Save(values ...*entity.SysDept) error
	First() (*entity.SysDept, error)
	Take() (*entity.SysDept, error)
	Last() (*entity.SysDept, error)
	Find() ([]*entity.SysDept, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SysDept, err error)
	FindInBatches(result *[]*entity.SysDept, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.SysDept) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDeptDo
	Assign(attrs ...field.AssignExpr) ISysDeptDo
	Joins(fields ...field.RelationField) ISysDeptDo
	Preload(fields ...field.RelationField) ISysDeptDo
	FirstOrInit() (*entity.SysDept, error)
	FirstOrCreate() (*entity.SysDept, error)
	FindByPage(offset int, limit int) (result []*entity.SysDept, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDeptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDeptDo) Debug() ISysDeptDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDeptDo) WithContext(ctx context.Context) ISysDeptDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDeptDo) ReadDB() ISysDeptDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDeptDo) WriteDB() ISysDeptDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDeptDo) Session(config *gorm.Session) ISysDeptDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDeptDo) Clauses(conds ...clause.Expression) ISysDeptDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDeptDo) Returning(value interface{}, columns ...string) ISysDeptDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDeptDo) Not(conds ...gen.Condition) ISysDeptDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDeptDo) Or(conds ...gen.Condition) ISysDeptDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDeptDo) Select(conds ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDeptDo) Where(conds ...gen.Condition) ISysDeptDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDeptDo) Order(conds ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDeptDo) Distinct(cols ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDeptDo) Omit(cols ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDeptDo) Join(table schema.Tabler, on ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDeptDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDeptDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDeptDo) Group(cols ...field.Expr) ISysDeptDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDeptDo) Having(conds ...gen.Condition) ISysDeptDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDeptDo) Limit(limit int) ISysDeptDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDeptDo) Offset(offset int) ISysDeptDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDeptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDeptDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDeptDo) Unscoped() ISysDeptDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDeptDo) Create(values ...*entity.SysDept) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDeptDo) CreateInBatches(values []*entity.SysDept, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDeptDo) Save(values ...*entity.SysDept) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDeptDo) First() (*entity.SysDept, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysDept), nil
	}
}

func (s sysDeptDo) Take() (*entity.SysDept, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysDept), nil
	}
}

func (s sysDeptDo) Last() (*entity.SysDept, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysDept), nil
	}
}

func (s sysDeptDo) Find() ([]*entity.SysDept, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SysDept), err
}

func (s sysDeptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SysDept, err error) {
	buf := make([]*entity.SysDept, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDeptDo) FindInBatches(result *[]*entity.SysDept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDeptDo) Attrs(attrs ...field.AssignExpr) ISysDeptDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDeptDo) Assign(attrs ...field.AssignExpr) ISysDeptDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDeptDo) Joins(fields ...field.RelationField) ISysDeptDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDeptDo) Preload(fields ...field.RelationField) ISysDeptDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDeptDo) FirstOrInit() (*entity.SysDept, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysDept), nil
	}
}

func (s sysDeptDo) FirstOrCreate() (*entity.SysDept, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SysDept), nil
	}
}

func (s sysDeptDo) FindByPage(offset int, limit int) (result []*entity.SysDept, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDeptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDeptDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDeptDo) Delete(models ...*entity.SysDept) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDeptDo) withDO(do gen.Dao) *sysDeptDo {
	s.DO = *do.(*gen.DO)
	return s
}
