// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Dept         *dept
	DictData     *dictData
	DictType     *dictType
	LoginLog     *loginLog
	Menu         *menu
	OperationLog *operationLog
	Post         *post
	Role         *role
	RoleMenu     *roleMenu
	User         *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Dept = &Q.Dept
	DictData = &Q.DictData
	DictType = &Q.DictType
	LoginLog = &Q.LoginLog
	Menu = &Q.Menu
	OperationLog = &Q.OperationLog
	Post = &Q.Post
	Role = &Q.Role
	RoleMenu = &Q.RoleMenu
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Dept:         newDept(db, opts...),
		DictData:     newDictData(db, opts...),
		DictType:     newDictType(db, opts...),
		LoginLog:     newLoginLog(db, opts...),
		Menu:         newMenu(db, opts...),
		OperationLog: newOperationLog(db, opts...),
		Post:         newPost(db, opts...),
		Role:         newRole(db, opts...),
		RoleMenu:     newRoleMenu(db, opts...),
		User:         newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Dept         dept
	DictData     dictData
	DictType     dictType
	LoginLog     loginLog
	Menu         menu
	OperationLog operationLog
	Post         post
	Role         role
	RoleMenu     roleMenu
	User         user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Dept:         q.Dept.clone(db),
		DictData:     q.DictData.clone(db),
		DictType:     q.DictType.clone(db),
		LoginLog:     q.LoginLog.clone(db),
		Menu:         q.Menu.clone(db),
		OperationLog: q.OperationLog.clone(db),
		Post:         q.Post.clone(db),
		Role:         q.Role.clone(db),
		RoleMenu:     q.RoleMenu.clone(db),
		User:         q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Dept:         q.Dept.replaceDB(db),
		DictData:     q.DictData.replaceDB(db),
		DictType:     q.DictType.replaceDB(db),
		LoginLog:     q.LoginLog.replaceDB(db),
		Menu:         q.Menu.replaceDB(db),
		OperationLog: q.OperationLog.replaceDB(db),
		Post:         q.Post.replaceDB(db),
		Role:         q.Role.replaceDB(db),
		RoleMenu:     q.RoleMenu.replaceDB(db),
		User:         q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Dept         *deptDo
	DictData     *dictDataDo
	DictType     *dictTypeDo
	LoginLog     *loginLogDo
	Menu         *menuDo
	OperationLog *operationLogDo
	Post         *postDo
	Role         *roleDo
	RoleMenu     *roleMenuDo
	User         *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Dept:         q.Dept.WithContext(ctx),
		DictData:     q.DictData.WithContext(ctx),
		DictType:     q.DictType.WithContext(ctx),
		LoginLog:     q.LoginLog.WithContext(ctx),
		Menu:         q.Menu.WithContext(ctx),
		OperationLog: q.OperationLog.WithContext(ctx),
		Post:         q.Post.WithContext(ctx),
		Role:         q.Role.WithContext(ctx),
		RoleMenu:     q.RoleMenu.WithContext(ctx),
		User:         q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
