// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sweet/internal/apps/system/types/entity"
)

func newDept(db *gorm.DB, opts ...gen.DOOption) dept {
	_dept := dept{}

	_dept.deptDo.UseDB(db, opts...)
	_dept.deptDo.UseModel(&entity.Dept{})

	tableName := _dept.deptDo.TableName()
	_dept.ALL = field.NewAsterisk(tableName)
	_dept.ID = field.NewInt64(tableName, "id")
	_dept.Pid = field.NewInt64(tableName, "pid")
	_dept.Name = field.NewString(tableName, "name")
	_dept.Code = field.NewString(tableName, "code")
	_dept.Ancestors = field.NewString(tableName, "ancestors")
	_dept.Leader = field.NewString(tableName, "leader")
	_dept.Phone = field.NewString(tableName, "phone")
	_dept.Email = field.NewString(tableName, "email")
	_dept.Sort = field.NewInt64(tableName, "sort")
	_dept.Status = field.NewInt64(tableName, "status")
	_dept.CreatedBy = field.NewInt64(tableName, "created_by")
	_dept.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_dept.CreatedAt = field.NewTime(tableName, "created_at")
	_dept.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dept.DeletedAt = field.NewField(tableName, "deleted_at")
	_dept.Version = field.NewInt64(tableName, "version")

	_dept.fillFieldMap()

	return _dept
}

// dept 部门表
type dept struct {
	deptDo

	ALL       field.Asterisk
	ID        field.Int64  // 部门ID
	Pid       field.Int64  // 父部门ID
	Name      field.String // 部门名称
	Code      field.String // 部门编码
	Ancestors field.String // 祖级列表
	Leader    field.String // 负责人
	Phone     field.String // 联系电话
	Email     field.String // 邮箱
	Sort      field.Int64  // 排序
	Status    field.Int64  // 状态 1-正常 2-禁用
	CreatedBy field.Int64  // 创建人
	UpdatedBy field.Int64  // 更新人
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间
	Version   field.Int64  // 乐观锁版本

	fieldMap map[string]field.Expr
}

func (d dept) Table(newTableName string) *dept {
	d.deptDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dept) As(alias string) *dept {
	d.deptDo.DO = *(d.deptDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dept) updateTableName(table string) *dept {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Pid = field.NewInt64(table, "pid")
	d.Name = field.NewString(table, "name")
	d.Code = field.NewString(table, "code")
	d.Ancestors = field.NewString(table, "ancestors")
	d.Leader = field.NewString(table, "leader")
	d.Phone = field.NewString(table, "phone")
	d.Email = field.NewString(table, "email")
	d.Sort = field.NewInt64(table, "sort")
	d.Status = field.NewInt64(table, "status")
	d.CreatedBy = field.NewInt64(table, "created_by")
	d.UpdatedBy = field.NewInt64(table, "updated_by")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewField(table, "deleted_at")
	d.Version = field.NewInt64(table, "version")

	d.fillFieldMap()

	return d
}

func (d *dept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dept) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 19)
	d.fieldMap["id"] = d.ID
	d.fieldMap["pid"] = d.Pid
	d.fieldMap["name"] = d.Name
	d.fieldMap["code"] = d.Code
	d.fieldMap["ancestors"] = d.Ancestors
	d.fieldMap["leader"] = d.Leader
	d.fieldMap["phone"] = d.Phone
	d.fieldMap["email"] = d.Email
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["status"] = d.Status
	d.fieldMap["created_by"] = d.CreatedBy
	d.fieldMap["updated_by"] = d.UpdatedBy
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
	d.fieldMap["version"] = d.Version

}

func (d dept) clone(db *gorm.DB) dept {
	d.deptDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dept) replaceDB(db *gorm.DB) dept {
	d.deptDo.ReplaceDB(db)
	return d
}

type deptDo struct{ gen.DO }

func (d deptDo) Debug() *deptDo {
	return d.withDO(d.DO.Debug())
}

func (d deptDo) WithContext(ctx context.Context) *deptDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deptDo) ReadDB() *deptDo {
	return d.Clauses(dbresolver.Read)
}

func (d deptDo) WriteDB() *deptDo {
	return d.Clauses(dbresolver.Write)
}

func (d deptDo) Session(config *gorm.Session) *deptDo {
	return d.withDO(d.DO.Session(config))
}

func (d deptDo) Clauses(conds ...clause.Expression) *deptDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deptDo) Returning(value interface{}, columns ...string) *deptDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deptDo) Not(conds ...gen.Condition) *deptDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deptDo) Or(conds ...gen.Condition) *deptDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deptDo) Select(conds ...field.Expr) *deptDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deptDo) Where(conds ...gen.Condition) *deptDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deptDo) Order(conds ...field.Expr) *deptDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deptDo) Distinct(cols ...field.Expr) *deptDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deptDo) Omit(cols ...field.Expr) *deptDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deptDo) Join(table schema.Tabler, on ...field.Expr) *deptDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deptDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deptDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deptDo) RightJoin(table schema.Tabler, on ...field.Expr) *deptDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deptDo) Group(cols ...field.Expr) *deptDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deptDo) Having(conds ...gen.Condition) *deptDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deptDo) Limit(limit int) *deptDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deptDo) Offset(offset int) *deptDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deptDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deptDo) Unscoped() *deptDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deptDo) Create(values ...*entity.Dept) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deptDo) CreateInBatches(values []*entity.Dept, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deptDo) Save(values ...*entity.Dept) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deptDo) First() (*entity.Dept, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Dept), nil
	}
}

func (d deptDo) Take() (*entity.Dept, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Dept), nil
	}
}

func (d deptDo) Last() (*entity.Dept, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Dept), nil
	}
}

func (d deptDo) Find() ([]*entity.Dept, error) {
	result, err := d.DO.Find()
	return result.([]*entity.Dept), err
}

func (d deptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Dept, err error) {
	buf := make([]*entity.Dept, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deptDo) FindInBatches(result *[]*entity.Dept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deptDo) Attrs(attrs ...field.AssignExpr) *deptDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deptDo) Assign(attrs ...field.AssignExpr) *deptDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deptDo) Joins(fields ...field.RelationField) *deptDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deptDo) Preload(fields ...field.RelationField) *deptDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deptDo) FirstOrInit() (*entity.Dept, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Dept), nil
	}
}

func (d deptDo) FirstOrCreate() (*entity.Dept, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Dept), nil
	}
}

func (d deptDo) FindByPage(offset int, limit int) (result []*entity.Dept, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deptDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deptDo) Delete(models ...*entity.Dept) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deptDo) withDO(do gen.Dao) *deptDo {
	d.DO = *do.(*gen.DO)
	return d
}
