// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysLoginLog = "sw_sys_login_log"

// SysLoginLog 系统登录日志表
type SysLoginLog struct {
	ID         int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:日志ID" json:"id"`                                          // 日志ID
	UserID     *int64         `gorm:"column:user_id;type:bigint unsigned;comment:用户ID" json:"user_id"`                                                              // 用户ID
	Username   string         `gorm:"column:username;type:varchar(64);not null;comment:登录用户名" json:"username"`                                                      // 登录用户名
	LoginType  *int64         `gorm:"column:login_type;type:tinyint(1);not null;default:1;comment:登录类型（1账号密码 2手机验证码 3邮箱验证码 4第三方登录 5微信 6QQ 7支付宝）" json:"login_type"` // 登录类型（1账号密码 2手机验证码 3邮箱验证码 4第三方登录 5微信 6QQ 7支付宝）
	ClientType *int64         `gorm:"column:client_type;type:tinyint(1);not null;default:1;comment:客户端类型（1Web 2移动端 3小程序 4API 5管理后台）" json:"client_type"`            // 客户端类型（1Web 2移动端 3小程序 4API 5管理后台）
	IP         string         `gorm:"column:ip;type:varchar(45);not null;comment:登录IP" json:"ip"`                                                                   // 登录IP
	Location   *string        `gorm:"column:location;type:varchar(64);comment:IP归属地" json:"location"`                                                               // IP归属地
	UserAgent  *string        `gorm:"column:user_agent;type:text;comment:用户代理" json:"user_agent"`                                                                   // 用户代理
	DeviceInfo *string        `gorm:"column:device_info;type:varchar(64);comment:设备信息" json:"device_info"`                                                          // 设备信息
	Browser    *string        `gorm:"column:browser;type:varchar(100);comment:浏览器" json:"browser"`                                                                  // 浏览器
	Os         *string        `gorm:"column:os;type:varchar(100);comment:操作系统" json:"os"`                                                                           // 操作系统
	Status     *int64         `gorm:"column:status;type:tinyint(1);not null;default:1;comment:登录状态（1成功 2失败 3异常）" json:"status"`                                     // 登录状态（1成功 2失败 3异常）
	FailReason *string        `gorm:"column:fail_reason;type:varchar(64);comment:失败原因" json:"fail_reason"`                                                          // 失败原因
	CreatedAt  *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                            // 创建时间
	UpdatedAt  *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                            // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                                               // 删除时间
	User       *SysUser       `gorm:"foreignKey:UserID;references:ID" json:"user"`
}

// TableName SysLoginLog's table name
func (*SysLoginLog) TableName() string {
	return TableNameSysLoginLog
}
