// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDept = "sw_sys_dept"

// SysDept 部门表
type SysDept struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:部门ID" json:"id"`               // 部门ID
	ParentID  *int64         `gorm:"column:parent_id;type:bigint unsigned;comment:父部门ID" json:"parent_id"`                              // 父部门ID
	Name      string         `gorm:"column:name;type:varchar(64);not null;comment:部门名称" json:"name"`                                    // 部门名称
	Code      *string        `gorm:"column:code;type:varchar(64);comment:部门编码" json:"code"`                                             // 部门编码
	Sort      int64          `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                                     // 排序
	Status    *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态: 1-启用, 2-禁用" json:"status"`       // 状态: 1-启用, 2-禁用
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	Parent    *SysDept       `gorm:"foreignKey:ParentID;references:ID" json:"parent"`
	Children  []*SysDept     `gorm:"foreignKey:ParentID;references:ID" json:"children"`
}

// TableName SysDept's table name
func (*SysDept) TableName() string {
	return TableNameSysDept
}
