// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSysRoleMenu = "sw_sys_role_menu"

// SysRoleMenu 角色菜单关联表
type SysRoleMenu struct {
	RoleID int64    `gorm:"column:role_id;type:bigint unsigned;primaryKey;comment:角色ID" json:"role_id"` // 角色ID
	MenuID int64    `gorm:"column:menu_id;type:bigint unsigned;primaryKey;comment:菜单ID" json:"menu_id"` // 菜单ID
	Role   *SysRole `gorm:"foreignKey:RoleID;references:ID" json:"role"`
	Menu   *SysMenu `gorm:"foreignKey:MenuID;references:ID" json:"menu"`
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
