// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysMenu = "sw_sys_menu"

// SysMenu 菜单表
type SysMenu struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:菜单ID" json:"id"`               // 菜单ID
	Name      string         `gorm:"column:name;type:varchar(64);not null;comment:组件名称/路由名称" json:"name"`                               // 组件名称/路由名称
	Title     string         `gorm:"column:title;type:varchar(64);not null;comment:菜单名称" json:"title"`                                  // 菜单名称
	ParentID  *int64         `gorm:"column:parent_id;type:bigint unsigned;comment:父菜单ID" json:"parent_id"`                              // 父菜单ID
	Path      *string        `gorm:"column:path;type:varchar(255);comment:路由地址" json:"path"`                                            // 路由地址
	Component *string        `gorm:"column:component;type:varchar(255);comment:组件地址" json:"component"`                                  // 组件地址
	MenuType  *int64         `gorm:"column:menu_type;type:tinyint(1);default:1;comment:菜单类型（1 目录 2 菜单 3 按钮）" json:"menu_type"`          // 菜单类型（1 目录 2 菜单 3 按钮）
	Status    *int64         `gorm:"column:status;type:tinyint(1);not null;default:1;comment:菜单状态(1 正常 2 停用)" json:"status"`            // 菜单状态(1 正常 2 停用)
	Perms     *string        `gorm:"column:perms;type:varchar(64);comment:权限标识" json:"perms"`                                           // 权限标识
	Icon      *string        `gorm:"column:icon;type:varchar(128);comment:菜单图标" json:"icon"`                                            // 菜单图标
	Order_    *int64         `gorm:"column:order;type:int;comment:显示顺序 从大到小" json:"order"`                                              // 显示顺序 从大到小
	Remark    *string        `gorm:"column:remark;type:varchar(128);comment:备注" json:"remark"`                                          // 备注
	CreateBy  *int64         `gorm:"column:create_by;type:bigint unsigned;comment:创建者" json:"create_by"`                                // 创建者
	UpdateBy  *int64         `gorm:"column:update_by;type:bigint unsigned;comment:更新者" json:"update_by"`                                // 更新者
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	Parent    *SysMenu       `gorm:"foreignKey:ParentID;references:ID" json:"parent"`
	Children  []*SysMenu     `gorm:"foreignKey:ParentID;references:ID" json:"children"`
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
