// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysApi = "sw_sys_api"

// SysApi API接口表
type SysApi struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:API ID" json:"id"`             // API ID
	Name        string         `gorm:"column:name;type:varchar(64);not null;comment:API名称" json:"name"`                                   // API名称
	Path        string         `gorm:"column:path;type:varchar(255);not null;comment:API路径" json:"path"`                                  // API路径
	Method      string         `gorm:"column:method;type:varchar(10);not null;comment:HTTP方法" json:"method"`                              // HTTP方法
	Group_      *string        `gorm:"column:group;type:varchar(64);comment:API分组" json:"group"`                                          // API分组
	Description *string        `gorm:"column:description;type:varchar(255);comment:API描述" json:"description"`                             // API描述
	Status      *int64         `gorm:"column:status;type:tinyint(1);not null;default:1;comment:API状态（1正常 2停用）" json:"status"`             // API状态（1正常 2停用）
	IsAuth      *int64         `gorm:"column:is_auth;type:tinyint(1);not null;default:1;comment:是否需要认证（1需要 2不需要）" json:"is_auth"`         // 是否需要认证（1需要 2不需要）
	CreateBy    *int64         `gorm:"column:create_by;type:bigint unsigned;comment:创建者" json:"create_by"`                                // 创建者
	UpdateBy    *int64         `gorm:"column:update_by;type:bigint unsigned;comment:更新者" json:"update_by"`                                // 更新者
	CreatedAt   *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	ApiGroup    *SysApiGroup   `gorm:"foreignKey:Group;references:Code" json:"api_group"`
}

// TableName SysApi's table name
func (*SysApi) TableName() string {
	return TableNameSysApi
}
