// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSysMenuConfig = "sw_sys_menu_config"

// SysMenuConfig 菜单配置表
type SysMenuConfig struct {
	ID            int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"`                 // ID
	MenuID        int64      `gorm:"column:menu_id;type:bigint unsigned;not null;comment:菜单ID" json:"menu_id"`                          // 菜单ID
	Query         *string    `gorm:"column:query;type:json;comment:路由参数" json:"query"`                                                  // 路由参数
	IsFrame       *int64     `gorm:"column:is_frame;type:tinyint(1);default:2;comment:是否外联（1 是 2 否）" json:"is_frame"`                   // 是否外联（1 是 2 否）
	ShowBadge     *int64     `gorm:"column:show_badge;type:tinyint(1);default:2;comment:是否显示徽章（1 是 2 否）" json:"show_badge"`             // 是否显示徽章（1 是 2 否）
	ShowTextBadge *string    `gorm:"column:show_text_badge;type:varchar(24);comment:文本徽章内容" json:"show_text_badge"`                     // 文本徽章内容
	IsHide        *int64     `gorm:"column:is_hide;type:tinyint(1);default:2;comment:是否在菜单中隐藏（1 是 2 否）" json:"is_hide"`                 // 是否在菜单中隐藏（1 是 2 否）
	IsHideTab     *int64     `gorm:"column:is_hide_tab;type:tinyint(1);default:2;comment:是否在标签页中隐藏（1 是 2 否）" json:"is_hide_tab"`        // 是否在标签页中隐藏（1 是 2 否）
	Link          *string    `gorm:"column:link;type:varchar(255);comment:外链地址" json:"link"`                                            // 外链地址
	IsIframe      *int64     `gorm:"column:is_iframe;type:tinyint(1);default:2;comment:是否iframe（1 是 2 否）" json:"is_iframe"`             // 是否iframe（1 是 2 否）
	KeepAlive     *int64     `gorm:"column:keep_alive;type:tinyint(1);default:2;comment:是否缓存页面（1 是 2否）" json:"keep_alive"`              // 是否缓存页面（1 是 2否）
	FixedTab      *int64     `gorm:"column:fixed_tab;type:tinyint(1);default:2;comment:是否固定标签页（1 是 2 否）" json:"fixed_tab"`              // 是否固定标签页（1 是 2 否）
	IsFirstLevel  *int64     `gorm:"column:is_first_level;type:tinyint(1);default:2;comment:是否为一级菜单" json:"is_first_level"`             // 是否为一级菜单
	ActivePath    *string    `gorm:"column:active_path;type:varchar(255);comment:激活菜单路径" json:"active_path"`                            // 激活菜单路径
	CreatedAt     *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	Menu          *SysMenu   `gorm:"foreignKey:MenuID;references:ID" json:"menu"`
}

// TableName SysMenuConfig's table name
func (*SysMenuConfig) TableName() string {
	return TableNameSysMenuConfig
}
