// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSysOperationLog = "sw_sys_operation_log"

// SysOperationLog 系统操作日志表
type SysOperationLog struct {
	ID            int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:日志ID" json:"id"`               // 日志ID
	UserID        *int64     `gorm:"column:user_id;type:bigint unsigned;comment:操作用户ID" json:"user_id"`                                 // 操作用户ID
	Username      *string    `gorm:"column:username;type:varchar(64);comment:操作用户名" json:"username"`                                    // 操作用户名
	Module        string     `gorm:"column:module;type:varchar(50);not null;comment:操作模块" json:"module"`                                // 操作模块
	Operation     string     `gorm:"column:operation;type:varchar(50);not null;comment:操作类型" json:"operation"`                          // 操作类型
	Method        string     `gorm:"column:method;type:varchar(10);not null;comment:HTTP方法" json:"method"`                              // HTTP方法
	URL           string     `gorm:"column:url;type:varchar(255);not null;comment:请求URL" json:"url"`                                    // 请求URL
	IP            string     `gorm:"column:ip;type:varchar(45);not null;comment:操作IP" json:"ip"`                                        // 操作IP
	Location      *string    `gorm:"column:location;type:varchar(100);comment:IP归属地" json:"location"`                                   // IP归属地
	UserAgent     *string    `gorm:"column:user_agent;type:varchar(500);comment:用户代理" json:"user_agent"`                                // 用户代理
	RequestParams *string    `gorm:"column:request_params;type:text;comment:请求参数" json:"request_params"`                                // 请求参数
	ResponseData  *string    `gorm:"column:response_data;type:text;comment:响应数据" json:"response_data"`                                  // 响应数据
	Status        *int64     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:操作状态（1成功 2失败）" json:"status"`              // 操作状态（1成功 2失败）
	ErrorMsg      *string    `gorm:"column:error_msg;type:varchar(500);comment:错误信息" json:"error_msg"`                                  // 错误信息
	CostTime      *int64     `gorm:"column:cost_time;type:int unsigned;comment:耗时（毫秒）" json:"cost_time"`                                // 耗时（毫秒）
	CreatedAt     *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:操作时间" json:"created_at"` // 操作时间
	User          *SysUser   `gorm:"foreignKey:UserID;references:ID" json:"user"`
}

// TableName SysOperationLog's table name
func (*SysOperationLog) TableName() string {
	return TableNameSysOperationLog
}
