// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysPost = "sw_sys_post"

// SysPost 岗位表
type SysPost struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:岗位ID" json:"id"`               // 岗位ID
	DeptID    int64          `gorm:"column:dept_id;type:bigint unsigned;not null;comment:所属部门" json:"dept_id"`                          // 所属部门
	Name      string         `gorm:"column:name;type:varchar(64);not null;comment:岗位名称" json:"name"`                                    // 岗位名称
	Code      *string        `gorm:"column:code;type:varchar(64);comment:岗位编码" json:"code"`                                             // 岗位编码
	Sort      int64          `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                                     // 排序
	Status    *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态: 1-启用, 2-禁用" json:"status"`       // 状态: 1-启用, 2-禁用
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	Dept      *SysDept       `gorm:"foreignKey:DeptID;references:ID" json:"dept"`
}

// TableName SysPost's table name
func (*SysPost) TableName() string {
	return TableNameSysPost
}
