// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSysRoleApi = "sw_sys_role_api"

// SysRoleApi 角色API关联表
type SysRoleApi struct {
	RoleID int64    `gorm:"column:role_id;type:bigint unsigned;primaryKey;comment:角色ID" json:"role_id"` // 角色ID
	APIID  int64    `gorm:"column:api_id;type:bigint unsigned;primaryKey;comment:API ID" json:"api_id"` // API ID
	Role   *SysRole `gorm:"foreignKey:RoleID;references:ID" json:"role"`
	Api    *SysApi  `gorm:"foreignKey:ApiID;references:ID" json:"api"`
}

// TableName SysRoleApi's table name
func (*SysRoleApi) TableName() string {
	return TableNameSysRoleApi
}
