// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysFile = "sw_sys_file"

// SysFile 系统文件表
type SysFile struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:文件ID" json:"id"`                                          // 文件ID
	Name         string         `gorm:"column:name;type:varchar(64);not null;comment:文件名称" json:"name"`                                                               // 文件名称
	OriginalName string         `gorm:"column:original_name;type:varchar(64);not null;comment:原始文件名" json:"original_name"`                                            // 原始文件名
	FilePath     string         `gorm:"column:file_path;type:varchar(255);not null;comment:文件路径" json:"file_path"`                                                    // 文件路径
	FileURL      *string        `gorm:"column:file_url;type:varchar(255);comment:文件访问URL" json:"file_url"`                                                            // 文件访问URL
	FileSize     int64          `gorm:"column:file_size;type:bigint unsigned;not null;comment:文件大小（字节）" json:"file_size"`                                             // 文件大小（字节）
	FileType     string         `gorm:"column:file_type;type:varchar(32);not null;comment:文件类型/MIME类型" json:"file_type"`                                              // 文件类型/MIME类型
	FileExt      string         `gorm:"column:file_ext;type:varchar(20);not null;comment:文件扩展名" json:"file_ext"`                                                      // 文件扩展名
	Md5          string         `gorm:"column:md5;type:varchar(32);not null;comment:文件MD5值" json:"md5"`                                                               // 文件MD5值
	StorageType  *int64         `gorm:"column:storage_type;type:tinyint unsigned;not null;default:1;comment:存储类型：1=本地存储，2=阿里云OSS，3=腾讯云COS，4=七牛云" json:"storage_type"` // 存储类型：1=本地存储，2=阿里云OSS，3=腾讯云COS，4=七牛云
	UploadUserID *int64         `gorm:"column:upload_user_id;type:bigint unsigned;comment:上传用户ID" json:"upload_user_id"`                                              // 上传用户ID
	Status       *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态：1=正常，2=禁用" json:"status"`                                    // 状态：1=正常，2=禁用
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                            // 创建时间
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                            // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                                               // 删除时间
	UploadUser   *SysUser       `gorm:"foreignKey:UploadUserID;references:ID" json:"upload_user"`
}

// TableName SysFile's table name
func (*SysFile) TableName() string {
	return TableNameSysFile
}
