// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sw_sys_user"

// SysUser 系统管理员表
type SysUser struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:管理员ID" json:"id"`              // 管理员ID
	Username  string         `gorm:"column:username;type:varchar(32);not null;comment:登录用户名" json:"username"`                           // 登录用户名
	Password  string         `gorm:"column:password;type:varchar(128);not null;comment:登录密码" json:"password"`                           // 登录密码
	Salt      string         `gorm:"column:salt;type:varchar(32);not null;comment:密码盐" json:"salt"`                                     // 密码盐
	Realname  string         `gorm:"column:realname;type:varchar(32);not null;comment:真实姓名" json:"realname"`                            // 真实姓名
	Nickname  string         `gorm:"column:nickname;type:varchar(32);not null;comment:昵称" json:"nickname"`                              // 昵称
	Avatar    *string        `gorm:"column:avatar;type:varchar(255);comment:头像" json:"avatar"`                                          // 头像
	Email     *string        `gorm:"column:email;type:varchar(64);comment:邮箱" json:"email"`                                             // 邮箱
	Phone     *string        `gorm:"column:phone;type:varchar(20);comment:手机号" json:"phone"`                                            // 手机号
	Status    *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态：1=正常，2=禁用" json:"status"`         // 状态：1=正常，2=禁用
	RoleID    *int64         `gorm:"column:role_id;type:bigint unsigned;comment:角色ID" json:"role_id"`                                   // 角色ID
	DeptID    *int64         `gorm:"column:dept_id;type:bigint unsigned;comment:部门ID" json:"dept_id"`                                   // 部门ID
	PostID    *int64         `gorm:"column:post_id;type:bigint unsigned;comment:岗位ID" json:"post_id"`                                   // 岗位ID
	Remark    *string        `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                                          // 备注
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	Role      *SysRole       `gorm:"foreignKey:RoleID;references:ID" json:"role"`
	Dept      *SysDept       `gorm:"foreignKey:DeptID;references:ID" json:"dept"`
	Post      *SysPost       `gorm:"foreignKey:PostID;references:ID" json:"post"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
