// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRole = "sw_sys_role"

// SysRole 系统角色表
type SysRole struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:角色ID" json:"id"`               // 角色ID
	Name      string         `gorm:"column:name;type:varchar(32);not null;comment:角色名称" json:"name"`                                    // 角色名称
	Code      string         `gorm:"column:code;type:varchar(64);not null;comment:角色标识" json:"code"`                                    // 角色标识
	Sort      int64          `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                                     // 排序
	IsSystem  *int64         `gorm:"column:is_system;type:tinyint unsigned;not null;default:2;comment:是否系统内置：1=是，2否" json:"is_system"`  // 是否系统内置：1=是，2否
	IsSuper   *int64         `gorm:"column:is_super;type:tinyint unsigned;not null;default:2;comment:是否超级管理员：1=是，2否" json:"is_super"`   // 是否超级管理员：1=是，2否
	Status    *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态：1=正常，2=禁用" json:"status"`         // 状态：1=正常，2=禁用
	Remark    *string        `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                                          // 备注
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
