// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysApiGroup = "sw_sys_api_group"

// SysApiGroup API分组表
type SysApiGroup struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:分组ID" json:"id"`               // 分组ID
	Name        string         `gorm:"column:name;type:varchar(50);not null;comment:分组名称" json:"name"`                                    // 分组名称
	Code        string         `gorm:"column:code;type:varchar(50);not null;comment:分组编码" json:"code"`                                    // 分组编码
	Description *string        `gorm:"column:description;type:varchar(200);comment:分组描述" json:"description"`                              // 分组描述
	Sort        int64          `gorm:"column:sort;type:int;not null;comment:显示顺序" json:"sort"`                                            // 显示顺序
	Status      *int64         `gorm:"column:status;type:tinyint(1);not null;default:1;comment:分组状态（1正常 2停用）" json:"status"`              // 分组状态（1正常 2停用）
	CreateBy    *int64         `gorm:"column:create_by;type:bigint unsigned;comment:创建者" json:"create_by"`                                // 创建者
	UpdateBy    *int64         `gorm:"column:update_by;type:bigint unsigned;comment:更新者" json:"update_by"`                                // 更新者
	CreatedAt   *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName SysApiGroup's table name
func (*SysApiGroup) TableName() string {
	return TableNameSysApiGroup
}
